import{a as p,S as f,i as d}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const m="46607456-5552cc86243543e4de6027df0",g="https://pixabay.com/api/";async function h(r,t=1){try{return(await p.get(g,{params:{key:m,q:r,page:t,image_type:"photo",per_page:15}})).data}catch(n){throw console.error("Помилка при отриманні зображень:",n),n}}function w(r){const t=document.querySelector(".gallery"),n=r.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </a>
    `).join("");t.insertAdjacentHTML("beforeend",n);const{height:l}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:l*2,behavior:"smooth"})}function L(){const r=document.querySelector(".gallery");r.innerHTML=""}const b=document.getElementById("search-form");document.querySelector(".gallery");const a=document.getElementById("load-more"),u=document.getElementById("loader");let c=1,s="",E=new f(".gallery a",{captionsData:"alt",captionDelay:250});async function y(r=""){try{r&&(c=1,s=r),u.style.display="block",a.style.display="none";const t=await h(s,c);if(!t||!t.hits||t.hits.length===0){d.warning({title:"Error",message:"Something went wrong! Please try again later."});return}w(t.hits),E.refresh(),t.hits.length===15&&(a.style.display="block",c++)}catch{d.error({title:"Error",message:"Something went wrong! Please try again later."})}finally{u.style.display="none"}}b.addEventListener("submit",r=>{if(r.preventDefault(),s=r.currentTarget.elements.query.value.trim(),!s){d.error({title:"Error",message:"Please enter a search query!"});return}L(),a.style.display="none",y(s)});a.addEventListener("click",()=>{y()});
//# sourceMappingURL=index.js.map
