import{a as g,S as m,i}from"./assets/vendor-Qob_5Ba8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="46607456-5552cc86243543e4de6027df0",h="https://pixabay.com/api/";async function w(t,o=1){try{return(await g.get(h,{params:{key:p,q:t,page:o,image_type:"photo",per_page:15}})).data}catch(s){throw console.error("Помилка при отриманні зображень:",s),s}}function b(t){const o=document.querySelector(".gallery"),s=t.map(e=>`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </a>
    `).join("");o.insertAdjacentHTML("beforeend",s);const{height:a}=o.firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}function L(){const t=document.querySelector(".gallery");t.innerHTML=""}const E=document.getElementById("search-form"),v=document.querySelector(".gallery"),n=document.getElementById("load-more"),S=document.getElementById("loader");let d="",l=1;const u=15;let q=new m(".gallery a",{captionsData:"alt",captionDelay:250});function y(t=!1){S.style.display=t?"block":"none",n.style.display=t?"none":"block"}async function f(){y(!0);try{const t=await w(d,l,u);t.hits.length===0&&l===1?(i.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none"):(b(t.hits),q.refresh(),l*u>=t.totalHits?(n.style.display="none",i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."})):n.style.display="block",B())}catch{i.error({title:"Error",message:"Something went wrong! Please try again later."})}finally{y(!1)}}function B(){const t=v.firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}E.addEventListener("submit",t=>{if(t.preventDefault(),d=t.currentTarget.elements.query.value.trim(),!d){i.error({title:"Error",message:"Please enter a search query!"});return}l=1,L(),n.style.display="none",f()});n.addEventListener("click",()=>{l+=1,f()});
//# sourceMappingURL=index.js.map
